import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import DefaultLayout from './layouts/DefaultLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Spam Mail Application',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DefaultLayout></DefaultLayout>
        {children}
      </body>
    </html>
  );
}
