// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

// import RouteLayoutProvider from "./provider/routLayoutProvider";
// import DefaultLayout from "./(user)/layouts/DefaultLayout";
// import SideNav from "./components/SideAndTopBar/SideNav";
import { useRouter } from "next/navigation";
import { request } from "http";
// import { getAuthCookies } from "../../lib/CookiStore";
import React, { useEffect } from "react";
// import UnAuthenticateLayout from "./(user)/layouts/UnAuthenticatLayout";
import { getAuthCookies } from "../../../../lib/CookiStore";

const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let isAuthenticated = false;
  const auth = async () => {
    isAuthenticated = await getAuthCookies("isAuthenticated");
    // console.log("isAuthenticated", isAuthenticated);
  };
  useEffect(() => {
    auth();
  }, []);

  return <>{children}</>;
}
