// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import RouteLayoutProvider from './provider/routLayoutProvider';
import DefaultLayout from './layouts/DefaultLayout';
import SideNav from './components/SideNav';
import { useRouter } from 'next/navigation';
import { request } from 'http';
import { getAuthCookies } from '../../lib/CookiStore';
import React from 'react';
const inter = Inter({ subsets: ['latin'] });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RouteLayoutProvider>
          <DefaultLayout>{children}</DefaultLayout>
        </RouteLayoutProvider>
      </body>
    </html>
  );
}
